### ISSUE TITLE
UCI score display

### ISSUE THREAD

**Issue by rwbc** [Aryan1508/Bit-Genie#1]
Hi Aryan,

I discovered your nice little  and quite new chess program a few days ago.
In a previous compilation I noticed the missing time management, but you have added this now.

Today I compiled it again and it seems it is ready now for running vs. other programs,
it just has a littlle glitch in displaying the eval for GUIs, instead of a 'cp' value with three digits,
(cp actually means centipawn) it just shows one digit always

Thus when it has an eval between 0.00 and 0.99 it will always print cp 0 instead of something between 0 and 99
and if it has an eval of e.g. 2.00 and 2.99 it will always show cp 2. The GUI will interpret cp 2 as 0.02.

Examples:

```
>Bit-Genie_r107-64(1): go wtime 90478 btime 108859 movestogo 30
<Bit-Genie_r107-64(1): info depth 1 seldepth 4 nodes 65 score cp 0 time 34 pv f3e2 
<Bit-Genie_r107-64(1): info depth 2 seldepth 4 nodes 166 score cp 0 time 34 pv f3e2 f8c5 
<Bit-Genie_r107-64(1): info depth 3 seldepth 7 nodes 2976 score cp 0 time 35 pv f3f4 f8b4 d4e5 
<Bit-Genie_r107-64(1): info depth 4 seldepth 7 nodes 2946 score cp 0 time 37 pv f3f4 e8f6 d4e5 f8d6 
<Bit-Genie_r107-64(1): info depth 5 seldepth 10 nodes 38699 score cp 0 time 49 pv f3g4 e8d6 f5f6 g7f6 c4c5 
<Bit-Genie_r107-64(1): info depth 6 seldepth 10 nodes 93667 score cp 0 time 75 pv f3f4 e8d6 f5f6 g7f6 c4c5 d6c4 
<Bit-Genie_r107-64(1): info depth 7 seldepth 12 nodes 330986 score cp 0 time 163 pv f3e2 e8d6 f5f6 g7f6 e2d3 d6e8 d3e3 

```
```
>Bit-Genie_r107-64(1): go wtime 51778 btime 80347 movestogo 17
<Bit-Genie_r107-64(1): info depth 1 seldepth 1 nodes 13 score cp -2 time 33 pv c2b1 
<Bit-Genie_r107-64(1): info depth 2 seldepth 3 nodes 57 score cp -2 time 34 pv c2b1 c4c3 
<Bit-Genie_r107-64(1): info depth 3 seldepth 3 nodes 148 score cp -2 time 35 pv c2b1 c4c3 b1a1 
<Bit-Genie_r107-64(1): info depth 4 seldepth 5 nodes 834 score cp -2 time 35 pv c2b1 c4c3 b1a1 c3c2 
<Bit-Genie_r107-64(1): info depth 5 seldepth 7 nodes 4484 score cp -3 time 37 pv c2c1 e4c3 c1c2 c3a2 c2b1 
<Bit-Genie_r107-64(1): info depth 6 seldepth 8 nodes 31631 score cp -4 time 45 pv c2b1 c4d3 b1c1 e4c3 h2h3 c3a2 
<Bit-Genie_r107-64(1): info depth 7 seldepth 10 nodes 18790 score cp -4 time 50 pv c2b1 c4d3 b1c1 e4c3 h2h3 c3e2 c1b1 
```

Here is its first win vs. new releases Rustic Alpha 2

```
[Event "Test@CuteCGdv"]
[Site "RWBC-CAPPUCCINO Win7U64 Q8200 2.33Ghz + Nvidia GT 710"]
[Date "2021.03.19"]
[Round "3"]
[White "Rustic_Alpha2-64"]
[Black "Bit-Genie_r107-64"]
[Result "0-1"]
[ECO "A40"]
[GameDuration "00:03:29"]
[GameEndTime "2021-03-19T12:01:13.857 Mitteleuropäische Zeit"]
[GameStartTime "2021-03-19T11:57:43.896 Mitteleuropäische Zeit"]
[Opening "Queen's pawn"]
[PlyCount "76"]
[TimeControl "40/120"]

1. d4 {book} c6 {book} 2. Nf3 {book} d5 {book} 3. e3 {book} Bg4 {book}
4. Be2 {+0.40/7 1.92s} Nd7 {0.00/7 3.19s} 5. O-O {+0.55/7 1.94s}
e6 {0.00/7 3.19s} 6. Nc3 {+0.45/7 1.96s} Ngf6 {0.00/7 3.19s}
7. Ne5 {+0.30/7 1.69s} Bf5 {0.00/7 3.20s} 8. g4 {+0.70/6 2.02s}
Bg6 {0.00/7 3.20s} 9. Nxg6 {+0.75/7 2.04s} hxg6 {0.00/7 3.20s}
10. g5 {+0.65/7 2.07s} Ne4 {+0.01/7 3.20s} 11. f4 {+0.30/7 2.10s}
Nxg5 {+0.01/7 3.20s} 12. fxg5 {-0.35/7 2.12s} Qxg5+ {+0.01/7 3.21s}
13. Kf2 {-0.40/6 2.16s} Rxh2+ {+0.03/7 3.21s} 14. Ke1 {-0.35/6 2.19s}
Qh4+ {+0.03/7 3.21s} 15. Kd2 {-0.25/6 2.23s} e5 {+0.03/7 3.21s}
16. dxe5 {-0.35/7 2.27s} d4 {+0.03/7 3.21s} 17. exd4 {-0.50/6 2.30s}
Qxd4+ {+0.03/7 3.21s} 18. Ke1 {-3.70/6 2.35s} Qh4+ {+0.04/7 3.22s}
19. Kd2 {-3.80/6 2.39s} Nxe5 {+0.06/7 3.22s} 20. Nd5 {-4.87/6 1.86s}
Rd8 {+0.07/7 3.22s} 21. Kc3 {-6.40/7 2.46s} Rxd5 {+0.09/7 3.22s}
22. Rf4 {-8.20/7 2.56s} Rxd1 {+0.09/7 3.23s} 23. Rxh4 {-7.40/8 2.62s}
Rxe2 {+0.09/8 3.23s} 24. b3 {-7.27/7 2.68s} f5 {+0.09/7 3.23s}
25. Rh8 {-7.00/8 2.70s} Ree1 {+0.09/8 3.24s} 26. Kb2 {-7.10/8 2.83s}
f4 {+0.10/8 3.24s} 27. Rh7 {-7.70/7 2.91s} f3 {+0.11/8 3.24s}
28. Rh2 {-9.45/7 3.00s} Re2 {+0.12/8 3.25s} 29. Be3 {-12.55/8 3.10s}
Rxa1 {+0.15/8 3.25s} 30. Rxe2 {-13.50/9 2.87s} fxe2 {+0.16/9 3.26s}
31. Bd2 {-13.75/9 2.47s} Rd1 {+0.16/8 3.26s} 32. Bc3 {-18.30/8 3.58s}
Nf3 {+0.21/8 3.27s} 33. b4 {-19.25/8 3.77s} Nd2 {+0.23/8 3.27s}
34. Bxd2 {-21.70/9 3.99s} Rxd2 {+0.24/8 3.28s} 35. b5 {-M8/9 3.89s}
e1=Q {+M7/8 3.29s} 36. a4 {-M6/7 4.65s} Qd1 {+M5/7 3.30s} 37. bxc6 {-M4/7 5.12s}
Rxc2+ {+M3/7 3.31s} 38. Kb3 {-M2/6 5.81s} Qd3# {+M1/8 3.33s, Black mates} 0-1
```
Do you plan to make a pre-release, or would you mind, if I add it to my XB/UCI chronology?
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM

Guenther

**Comment by Aryan1508** [comment]
Hi Guenther, I have noted the error and I will fix it ASAP.  What the release, what is it that you're trying to do?

**Comment by rwbc** [comment]
I would like to add Bit-Genie to the list of available (and playable) XB/UCI programs.
In that case it it will probably be tested by various computerchess sites/people already.

If you think it is too early and you want to wait for a proper release version, I'll just wait.

Guenther

**Comment by Aryan1508** [comment]
I myself am not sure if this is too early or not, can you tell me a little more about it so i can decide?

**Comment by rwbc** [comment]
Well, that's not so easy to answer, but I think it is not too early and I found no heavy bugs so far.
(no illegal moves, no time losses, no meory leak, not using too much cpu-time, etc.)

Also there are a lot of much weaker programs already in the rating lists.
There is no disadvantage in currently announcing it, you'll get testers and support for free
and if the program will get stronger later, newer versions will be tested too. ;-)

The most known 'rating organisations' are CCRL and CEGT.
http://ccrl.chessdom.com/
http://www.cegt.net/

The Blitz rating list at CCRL has nearly 3000 (several versions per program) entries,
http://ccrl.chessdom.com/ccrl/404/rating_list_all.html
My estimation is that Bit-Genie right now would be rated 1750-1800 there.
(A test vs. a new version of Rustic is running here on my computer - 60 games played so far at 40 moves / 2 min.)
https://github.com/mvanthoor/rustic

BTW, if you have any programming questions or other questions regarding computerchess,
talkchess would be good place to look at.
http://talkchess.com/forum3/index.php

**Comment by Aryan1508** [comment]
Okay, I'm interested. What's my next step

**Comment by rwbc** [comment]
> 
> Okay, I'm interested. What's my next step

Either you make a (pre-)release version with a windows compilation, linux people usually compile themselves,
or you simply do nothing and I offer my compilation for first tests at talkchess and let Bit-Genie be widely known now
and follow what happens.

Of course you should still announce it at talkchess (might take a few days until you are registered for writing access)
and tell a few words about it and yourself. You could also try to register e.g. for the CCRL forum and announce it there,
may be registering there is faster. (I think so)

Ah and a last cosmetical thing you should add a kind of version number to the uci id for its name.
Something like 0.1 or 0.0.1 or what you like...

`std::cout << "id name Bit Genie $version$" << std::endl;`

A slight disclaimer too, beware that computerchess/chess can be quite addictive, but may be you know already ;-)

**Comment by Aryan1508** [comment]
I appreciate it, I have a few small questions, is it possible to
communicate somewhere so not to overflow this thread?

**Comment by rwbc** [comment]
Aryan, send me a mail to rwbc[@]gmx.de with your questions. (I included brackets just in case of possible spam bots)

Guenther

**Comment by Aryan1508** [comment]
Alright, Thank you
