### ISSUE TITLE
Support for larger hash sizes?

### ISSUE THREAD

**Issue by Cens0rs** [Aryan1508/Bit-Genie#190]
I downloaded Bit genie 9 compiled for windows to play against some engines. I tried to set the hash to 10 GB but the gui limited the hash to 3 GB. However, it would not initialize until I set it to 1.5 GB. If you are competing in TCEC, some engines use 256 GB. Not sure if you are interested in that but the engine not initializing is the issue.

**Comment by Aryan1508** [comment]
Could you be a little more specific? What do you mean by 'it would not initialize'? 

Regarding larger hash sizes, the max value is arbitrary, and I will push it so GUI's don't complain.

**Comment by Cens0rs** [comment]
Cute chess gives an error while arena does not but it never analyzes the position. Both have the hash set to 3000 MB.
![Cute chess Bit Genie 9 hash bug](https://user-images.githubusercontent.com/33385351/135786532-09844dc5-d205-4828-b3b6-14a340ba77a5.png)
![Arena Bit Genie 9 hash bug](https://user-images.githubusercontent.com/33385351/135786580-3d2e7d63-7456-4f77-934c-8fcb6990d213.png)
![Bit Genie 9 hash settings](https://user-images.githubusercontent.com/33385351/135786710-b54eaf95-8d50-4c90-86a7-172c8e8073b3.png)

**Comment by Cens0rs** [comment]
As I said previously, it wouldn't continue the tournament until I had set the hash to 1536 MB.

**Comment by Aryan1508** [comment]
Yes, cute-chess has an `Engine Debug`  option to view the output from/input to the engine. 

Currently, the `max` value mentioned in UCI is 3000, which is why you aren't able to set a higher value. But anything within this limit should work without problems.

**Comment by Cens0rs** [comment]
![Bit Genie 9 hash Debug](https://user-images.githubusercontent.com/33385351/135787521-26c9b4f0-e1f7-4813-b91a-98111318444b.png)
It seems like it never printed "readyok".
Here is what it prints vs. itself with both of them at 1536 MB hash:
![Bit Genie 9 1536 Hash Debug](https://user-images.githubusercontent.com/33385351/135787587-0ab02012-d205-4b63-97e5-e4f34faf27dc.png)

**Comment by Aryan1508** [comment]
Can you try running the executable externally and giving a `setoption name Hash value 3000` command? 

Something like this
```
> Bit-Genie.exe
setoption name Hash value 3000 
isready
```

**Comment by Cens0rs** [comment]
![Bit Genie 9 Hash Bug external](https://user-images.githubusercontent.com/33385351/135788139-434b9c92-c8fc-4d00-ac83-cc86cada8a19.png)

**Comment by Aryan1508** [comment]
Ah yes, this is what I was looking for. Let me see what's going on. Thank you

**Comment by Cens0rs** [comment]
No problem. If you need anything else, let me know.

**Comment by Aryan1508** [comment]
I have fixed the issue and merged the commit into master. Now it allows you to set a much larger hash, and doesn't overflow. 

You can compile the latest commit for a fix, or I can compile a binary for you. 

https://github.com/Aryan1508/Bit-Genie/commit/a37a287e762a479f5c48e35501df362b84eaa6c6 (Bit-Genie-a37a287)

**Comment by Cens0rs** [comment]
Thanks! I can compile it all good.
